spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_db?useSSL=false&serverTimezone=UTC
    username: root
    password: plmoknijb09
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
